PascoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizes.urls', namespace='quizes')),
    # path('', include('register.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path
from .views import (
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view
)

app_name = 'quizes'

urlpatterns = [
    path('', QuizListView.as_view(), name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
]

register/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.register, name='register')
]

questions/models.py
from django.db import models
from quizes.models import Quiz

class Question(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()

class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

quizes/models.py
from django.db import models
import random

DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="required score in %")
    difficluty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'

register/models.py
from django.db import models

# Create your models here.
class Register(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.username

results/models.py
from django.db import models
from quizes.models import Quiz
from django.contrib.auth.models import User
# Create your models here.
class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return self.user.username

register/forms.py
from django import forms
from .models import Register

class RegistrationForms(forms.ModelForm):
    class Meta:
        model = Register
        fields = '__all__'

questions/views.py
from django.shortcuts import render

# Create your views here.

quizes/views.py
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result

class QuizListView(ListView):
    model = Quiz 
    template_name = 'quizes/main.html'

def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})

def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

def save_quiz_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

register/views.py
from django.shortcuts import redirect, render
from.models import Register
from .forms import RegistrationForms
from django.contrib.auth import login, authenticate
from django.contrib import messages
# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegistrationForms(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            if Register.objects.filter(username=username).exists():
                messages.info(request, 'Invalid Credential')
                form = RegistrationForms()
            else:
                form.save()
                account = authenticate(username=username, email=email, password=password)
                login(request, account)
                return redirect('main-view/')
        else:
            form['registration_form'] = form
    else:
        form = RegistrationForms()
    context = {
        'form':form
    }
    return render(request, 'register.html', context)

results/views.py
from django.shortcuts import render

# Create your views here.

quizes/templates/quizes/main.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/main.js' %}" defer></script> 
{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-confirm"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">no</button>
        <button type="button" id="start-button" class="btn btn-success">yes</button>
      </div>
    </div>
  </div>
</div>

<div class="h1">Exam List</div>
<hr>
{% for obj in object_list %}
    <button
        class="btn btn-link modal-button"
        data-pk="{{obj.pk}}"
        data-quiz="{{obj.name}}"
        data-questions="{{obj.number_of_questions}}"
        data-difficulty="{{obj.difficluty}}"
        data-time="{{obj.time}}"
        data-pass = "{{obj.required_score_to_pass}}"
        data-toggle="modal"
        data-target="#quizStartModal">
        {{obj.name}}
    </button><br>

{% endfor %}
{% endblock content %}

quizes/templates/quizes/quiz.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script> 
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <b>{{obj.name}}</b>
        <p>score to pass: {{obj.required_score_to_pass}}%</p>
    </div>
    <div class="col text-right" id="timer-box"></div>
</div>

<a href="{% url 'quizes:main-view' %}" class="btn btn-danger">go back</a>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">save</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
    <link rel="stylesheet" href={% static 'style.css' %}>
    <link rel="stylesheet" href="style.css">

    {% block scripts %}
    {% endblock scripts %}

    <title>quiz app| {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  </body>
</html>

templates/register.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
    <!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Creative Colorlib SignUp Form</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
</head>
<body>
	<div class="main-w3layouts wrapper">
		<h1> SignUp and Login Form</h1>
		<div class="main-agileinfo">
			<div class="agileits-top">
				<form action="{% url 'register' %}" method="post">
                    {% csrf_token %}
                    {{form|crispy}}
					<!-- <input class="text" type="text" name="username" placeholder="Username" required="">
					<input class="text email" type="email" name="email" placeholder="Email" required="">
					<input class="text" type="password" name="password" placeholder="Password" required="">
					<input class="text w3lpass" type="password" name="password" placeholder="Confirm Password" required=""> -->
					<input type="submit" value="SIGNUP">
				</form>
				
</body>
</html>
{% endblock %}